import { ArrowLeft, Download, Copy, Check, AlertCircle, Package, Wrench, Activity, Info, Ticket } from "lucide-react";
import { useState, useEffect, useRef } from "react";
import { format } from "date-fns";
import type { Analysis } from "../services/api";
import StackTraceViewer from "./StackTraceViewer";
import CollapsibleSection from "./CollapsibleSection";
import MultiPartAnalysisViewer from "./MultiPartAnalysisViewer";
import JiraTicketModal from "./JiraTicketModal";
import { isJiraEnabled } from "../services/jira";

interface AnalysisDetailViewProps {
  analysis: Analysis;
  onBack: () => void;
}

export default function AnalysisDetailView({ analysis, onBack }: AnalysisDetailViewProps) {
  const [copied, setCopied] = useState(false);
  const [showJiraModal, setShowJiraModal] = useState(false);
  const [jiraEnabled, setJiraEnabled] = useState(false);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Check if JIRA is enabled
  useEffect(() => {
    isJiraEnabled().then(setJiraEnabled);
  }, []);

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, []);

  const getSeverityColor = (severity: string) => {
    switch (severity.toLowerCase()) {
      case "critical":
        return "bg-red-500/20 text-red-400 border-red-500/30";
      case "high":
        return "bg-orange-500/20 text-orange-400 border-orange-500/30";
      case "medium":
        return "bg-yellow-500/20 text-yellow-400 border-yellow-500/30";
      case "low":
        return "bg-blue-500/20 text-blue-400 border-blue-500/30";
      default:
        return "bg-gray-500/20 text-gray-400 border-gray-500/30";
    }
  };

  const handleCopyToClipboard = () => {
    const text = `
Analysis Report - ${analysis.filename}
=====================================

Error Type: ${analysis.error_type}
Severity: ${analysis.severity.toUpperCase()}
Analyzed: ${format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}
Model: ${analysis.ai_model}
Cost: $${analysis.cost.toFixed(4)}

ROOT CAUSE
----------
${analysis.root_cause}

SUGGESTED FIXES
---------------
${analysis.suggested_fixes}

---
Generated by Hadron - Smalltalk Crash Analyzer
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => setCopied(false), 2000);
  };

  const handleExportMarkdown = () => {
    const markdown = `# Analysis Report: ${analysis.filename}

**Error Type:** ${analysis.error_type}
**Severity:** ${analysis.severity.toUpperCase()}
**Analyzed:** ${format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}
**Model:** ${analysis.ai_model}
**Cost:** $${analysis.cost.toFixed(4)}

## Root Cause

${analysis.root_cause}

## Suggested Fixes

${analysis.suggested_fixes}

---

*Generated by Hadron - Smalltalk Crash Analyzer*
`;

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${analysis.filename.replace(/\.(txt|log)$/i, "")}-analysis.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Parse suggested fixes if it's a string
  const suggestedFixes = typeof analysis.suggested_fixes === "string"
    ? analysis.suggested_fixes.split("\n").filter((line) => line.trim())
    : analysis.suggested_fixes;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <button
          onClick={onBack}
          className="flex items-center gap-2 px-4 py-2 hover:bg-gray-700 rounded-lg transition"
        >
          <ArrowLeft className="w-5 h-5" />
          Back to History
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyToClipboard}
            className="flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg transition"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-green-400" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy Report
              </>
            )}
          </button>
          <button
            onClick={handleExportMarkdown}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg transition"
          >
            <Download className="w-4 h-4" />
            Export Markdown
          </button>
          {jiraEnabled && (
            <button
              onClick={() => setShowJiraModal(true)}
              className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 rounded-lg transition"
              title="Create JIRA ticket from this analysis"
            >
              <Ticket className="w-4 h-4" />
              Create JIRA Ticket
            </button>
          )}
        </div>
      </div>

      {/* File Info Card */}
      <div className="bg-gray-800 border border-gray-700 rounded-lg p-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <h2 className="text-2xl font-bold mb-2">{analysis.filename}</h2>
            <div className="flex items-center gap-3 text-sm text-gray-400">
              <span>{format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}</span>
              <span>•</span>
              <span>{analysis.file_size_kb.toFixed(1)} KB</span>
              <span>•</span>
              <span>{analysis.ai_model}</span>
              <span>•</span>
              <span>${analysis.cost.toFixed(4)}</span>
            </div>
          </div>
          <span
            className={`px-4 py-2 rounded-lg text-sm font-semibold border ${getSeverityColor(
              analysis.severity
            )}`}
          >
            {analysis.severity.toUpperCase()}
          </span>
        </div>

        {analysis.was_truncated && (
          <div className="mt-4 p-3 bg-yellow-500/10 border border-yellow-500/20 rounded-lg text-sm text-yellow-400">
            ⚠️ This file was truncated for analysis. Large portions may have been omitted.
          </div>
        )}
      </div>

      {/* Error Type */}
      <CollapsibleSection
        title="Error Type"
        icon={<AlertCircle className="w-5 h-5" />}
        badge={
          <span
            className={`px-3 py-1 rounded-lg text-xs font-semibold border ${getSeverityColor(
              analysis.severity
            )}`}
          >
            {analysis.severity.toUpperCase()}
          </span>
        }
      >
        <p className="text-gray-300 text-lg font-medium">{analysis.error_type}</p>

        {/* Error Message - if available */}
        {analysis.error_message && (
          <div className="mt-4 p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
            <div className="flex items-start gap-2">
              <AlertCircle className="w-4 h-4 text-red-400 mt-0.5 flex-shrink-0" />
              <p className="text-sm text-red-300">{analysis.error_message}</p>
            </div>
          </div>
        )}

        {/* Component - if available */}
        {analysis.component && (
          <div className="mt-3 flex items-center gap-2 text-sm">
            <Package className="w-4 h-4 text-blue-400" />
            <span className="text-gray-400">Affected Component:</span>
            <span className="text-blue-400 font-mono">{analysis.component}</span>
          </div>
        )}
      </CollapsibleSection>

      {/* Stack Trace - if available */}
      {analysis.stack_trace && (
        <CollapsibleSection
          title="Stack Trace"
          icon={<Activity className="w-5 h-5" />}
          defaultOpen={false}
        >
          <StackTraceViewer stackTrace={analysis.stack_trace} />
        </CollapsibleSection>
      )}

      {/* Root Cause - Multi-Part Analysis Viewer */}
      <MultiPartAnalysisViewer rootCause={analysis.root_cause} />

      {/* Suggested Fixes */}
      <CollapsibleSection
        title="Suggested Fixes"
        icon={<Wrench className="w-5 h-5" />}
        badge={
          Array.isArray(suggestedFixes) && (
            <span className="px-2 py-1 bg-blue-500/20 text-blue-400 rounded text-xs font-semibold">
              {suggestedFixes.length} {suggestedFixes.length === 1 ? 'Fix' : 'Fixes'}
            </span>
          )
        }
      >
        <div className="space-y-3">
          {Array.isArray(suggestedFixes) ? (
            suggestedFixes.map((fix, index) => (
              <div key={index} className="flex gap-3">
                <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center text-sm font-semibold">
                  {index + 1}
                </div>
                <p className="text-gray-300 flex-1">{fix}</p>
              </div>
            ))
          ) : (
            <div className="text-gray-300 whitespace-pre-wrap leading-relaxed">{suggestedFixes}</div>
          )}
        </div>
      </CollapsibleSection>

      {/* Metadata */}
      <CollapsibleSection
        title="Analysis Metadata"
        icon={<Info className="w-5 h-5" />}
        defaultOpen={false}
      >
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div>
            <span className="text-gray-400">Analysis ID:</span>
            <span className="ml-2 font-mono">{analysis.id}</span>
          </div>
          <div>
            <span className="text-gray-400">Tokens Used:</span>
            <span className="ml-2">{analysis.tokens_used.toLocaleString()}</span>
          </div>
          <div>
            <span className="text-gray-400">Model:</span>
            <span className="ml-2">{analysis.ai_model}</span>
          </div>
          {analysis.ai_provider && (
            <div>
              <span className="text-gray-400">Provider:</span>
              <span className="ml-2 capitalize">{analysis.ai_provider}</span>
            </div>
          )}
          {analysis.confidence && (
            <div>
              <span className="text-gray-400">Confidence:</span>
              <span className={`ml-2 font-semibold ${
                analysis.confidence === 'HIGH' ? 'text-green-400' :
                analysis.confidence === 'MEDIUM' ? 'text-yellow-400' :
                'text-orange-400'
              }`}>
                {analysis.confidence}
              </span>
            </div>
          )}
          <div>
            <span className="text-gray-400">Cost:</span>
            <span className="ml-2 text-green-400 font-semibold">${analysis.cost.toFixed(4)}</span>
          </div>
          {analysis.analysis_duration_ms && (
            <div>
              <span className="text-gray-400">Analysis Duration:</span>
              <span className="ml-2 text-blue-400 font-semibold">
                {(analysis.analysis_duration_ms / 1000).toFixed(2)}s
              </span>
            </div>
          )}
          <div>
            <span className="text-gray-400">File Size:</span>
            <span className="ml-2">{analysis.file_size_kb.toFixed(2)} KB</span>
          </div>
          <div>
            <span className="text-gray-400">Truncated:</span>
            <span className="ml-2">{analysis.was_truncated ? "Yes" : "No"}</span>
          </div>
          {analysis.is_favorite && (
            <div>
              <span className="text-gray-400">Favorite:</span>
              <span className="ml-2 text-yellow-400">★ Yes</span>
            </div>
          )}
          {analysis.view_count > 0 && (
            <div>
              <span className="text-gray-400">Views:</span>
              <span className="ml-2">{analysis.view_count}</span>
            </div>
          )}
        </div>
      </CollapsibleSection>

      {/* JIRA Ticket Modal */}
      <JiraTicketModal
        analysis={analysis}
        isOpen={showJiraModal}
        onClose={() => setShowJiraModal(false)}
      />
    </div>
  );
}
