import { ArrowLeft, Download, Copy, Check, AlertCircle, Package, Wrench, Activity, Info, Ticket, Settings2, Zap, Search, Gauge, Link2, ExternalLink, Shield } from "lucide-react";
import { useState, useEffect, useRef } from "react";
import { format } from "date-fns";
import type { Analysis } from "../services/api";
import StackTraceViewer from "./StackTraceViewer";
import CollapsibleSection from "./CollapsibleSection";
import MultiPartAnalysisViewer from "./MultiPartAnalysisViewer";
import JiraTicketModal from "./JiraTicketModal";
import ExportDialog from "./ExportDialog";
import LinkedTickets from "./LinkedTickets";
import JiraSyncStatus from "./JiraSyncStatus";
import { isJiraEnabled } from "../services/jira";

interface AnalysisDetailViewProps {
  analysis: Analysis;
  onBack: () => void;
}

export default function AnalysisDetailView({ analysis, onBack }: AnalysisDetailViewProps) {
  const [copied, setCopied] = useState(false);
  const [showJiraModal, setShowJiraModal] = useState(false);
  const [showExportDialog, setShowExportDialog] = useState(false);
  const [jiraEnabled, setJiraEnabled] = useState(false);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Check if JIRA is enabled
  useEffect(() => {
    isJiraEnabled().then(setJiraEnabled);
  }, []);

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, []);

  const getSeverityColor = (severity: string) => {
    switch (severity.toLowerCase()) {
      case "critical":
        return "bg-red-500/20 text-red-400 border-red-500/30";
      case "high":
        return "bg-orange-500/20 text-orange-400 border-orange-500/30";
      case "medium":
        return "bg-yellow-500/20 text-yellow-400 border-yellow-500/30";
      case "low":
        return "bg-blue-500/20 text-blue-400 border-blue-500/30";
      default:
        return "bg-gray-500/20 text-gray-400 border-gray-500/30";
    }
  };

  const handleCopyToClipboard = () => {
    const text = `
Analysis Report - ${analysis.filename}
=====================================

Error Type: ${analysis.error_type}
Severity: ${analysis.severity.toUpperCase()}
Analyzed: ${format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}
Model: ${analysis.ai_model}
Cost: $${analysis.cost.toFixed(4)}

ROOT CAUSE
----------
${analysis.root_cause}

SUGGESTED FIXES
---------------
${analysis.suggested_fixes}

---
Generated by Hadron - Smalltalk Crash Analyzer
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => setCopied(false), 2000);
  };

  const handleExportMarkdown = () => {
    const markdown = `# Analysis Report: ${analysis.filename}

**Error Type:** ${analysis.error_type}
**Severity:** ${analysis.severity.toUpperCase()}
**Analyzed:** ${format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}
**Model:** ${analysis.ai_model}
**Cost:** $${analysis.cost.toFixed(4)}

## Root Cause

${analysis.root_cause}

## Suggested Fixes

${analysis.suggested_fixes}

---

*Generated by Hadron - Smalltalk Crash Analyzer*
`;

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${analysis.filename.replace(/\.(txt|log)$/i, "")}-analysis.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Parse suggested fixes if it's a string
  const suggestedFixes = typeof analysis.suggested_fixes === "string"
    ? analysis.suggested_fixes.split("\n").filter((line) => line.trim())
    : analysis.suggested_fixes;

  // Parse Sentry metadata from full_data (if sentry analysis)
  const sentryData = analysis.analysis_type === "sentry" && analysis.full_data
    ? parseSentryFullData(analysis.full_data)
    : null;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <button
          onClick={onBack}
          className="flex items-center gap-2 px-4 py-2 hover:bg-gray-700 rounded-lg transition"
        >
          <ArrowLeft className="w-5 h-5" />
          Back to History
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyToClipboard}
            className="flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg transition"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-green-400" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy Report
              </>
            )}
          </button>
          <button
            onClick={handleExportMarkdown}
            className="flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg transition"
            title="Quick export to Markdown"
          >
            <Download className="w-4 h-4" />
            Quick Export
          </button>
          <button
            onClick={() => setShowExportDialog(true)}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg transition"
            title="Advanced export options"
          >
            <Settings2 className="w-4 h-4" />
            Export Options
          </button>
          {jiraEnabled && (
            <button
              onClick={() => setShowJiraModal(true)}
              className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 rounded-lg transition"
              title="Create JIRA ticket from this analysis"
            >
              <Ticket className="w-4 h-4" />
              Create JIRA Ticket
            </button>
          )}
          {sentryData?.permalink && (
            <a
              href={sentryData.permalink}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 px-4 py-2 bg-orange-600 hover:bg-orange-700 rounded-lg transition"
              title="View this issue in Sentry"
            >
              <ExternalLink className="w-4 h-4" />
              View in Sentry
            </a>
          )}
        </div>
      </div>

      {/* File Info Card */}
      <div className="bg-gray-800 border border-gray-700 rounded-lg p-6">
        <div className="flex items-start justify-between mb-4">
          <div>
            <h2 className="text-2xl font-bold mb-2">{analysis.filename}</h2>
            <div className="flex items-center gap-3 text-sm text-gray-400">
              <span>{format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}</span>
              <span>•</span>
              <span>{analysis.file_size_kb.toFixed(1)} KB</span>
              <span>•</span>
              <span>{analysis.ai_model}</span>
              <span>•</span>
              <span>${analysis.cost.toFixed(4)}</span>
            </div>
          </div>
          <span
            className={`px-4 py-2 rounded-lg text-sm font-semibold border ${getSeverityColor(
              analysis.severity
            )}`}
          >
            {analysis.severity.toUpperCase()}
          </span>
        </div>

        {/* Sentry Issue Metadata */}
        {sentryData && (
          <div className="mt-4 flex flex-wrap items-center gap-3 text-sm">
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 bg-orange-500/10 border border-orange-500/20 rounded-lg text-orange-400">
              <Shield className="w-3.5 h-3.5" />
              Sentry Issue
            </span>
            {sentryData.shortId && (
              <span className="text-gray-400">
                <span className="text-gray-500">ID:</span>{" "}
                <span className="font-mono text-gray-300">{sentryData.shortId}</span>
              </span>
            )}
            {sentryData.platform && (
              <span className="text-gray-400">
                <span className="text-gray-500">Platform:</span> {sentryData.platform}
              </span>
            )}
            {sentryData.count && (
              <span className="text-gray-400">
                <span className="text-gray-500">Events:</span> {sentryData.count}
              </span>
            )}
            {sentryData.userCount != null && sentryData.userCount > 0 && (
              <span className="text-gray-400">
                <span className="text-gray-500">Users:</span> {sentryData.userCount}
              </span>
            )}
            {sentryData.level && (
              <span className={`px-1.5 py-0.5 rounded text-xs font-medium ${
                sentryData.level === "fatal" ? "bg-red-600 text-white" :
                sentryData.level === "error" ? "bg-red-500/20 text-red-400" :
                sentryData.level === "warning" ? "bg-yellow-500/20 text-yellow-400" :
                "bg-gray-500/20 text-gray-400"
              }`}>
                {sentryData.level}
              </span>
            )}
          </div>
        )}

        {/* Token-Safe Analysis Metadata */}
        {analysis.analysis_mode && (
          <div className="mt-4 flex flex-wrap items-center gap-2">
            {/* Analysis Mode Badge */}
            <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium ${
              analysis.analysis_mode === "Deep Scan"
                ? "bg-purple-500/20 text-purple-400 border border-purple-500/30"
                : analysis.analysis_mode?.includes("Extracted")
                  ? "bg-amber-500/20 text-amber-400 border border-amber-500/30"
                  : "bg-green-500/20 text-green-400 border border-green-500/30"
            }`}>
              {analysis.analysis_mode === "Deep Scan" ? (
                <Search className="w-3.5 h-3.5" />
              ) : (
                <Zap className="w-3.5 h-3.5" />
              )}
              {analysis.analysis_mode}
            </span>

            {/* Token Utilization Badge */}
            {analysis.token_utilization !== undefined && (
              <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium ${
                analysis.token_utilization > 80
                  ? "bg-orange-500/20 text-orange-400 border border-orange-500/30"
                  : analysis.token_utilization > 50
                    ? "bg-yellow-500/20 text-yellow-400 border border-yellow-500/30"
                    : "bg-cyan-500/20 text-cyan-400 border border-cyan-500/30"
              }`}>
                <Gauge className="w-3.5 h-3.5" />
                {analysis.token_utilization.toFixed(0)}% Token Usage
              </span>
            )}

            {/* Coverage Summary */}
            {analysis.coverage_summary && (
              <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium bg-gray-700/50 text-gray-300 border border-gray-600">
                <Info className="w-3.5 h-3.5" />
                {analysis.coverage_summary}
              </span>
            )}
          </div>
        )}

        {/* Sentry Detected Pattern Badges */}
        {analysis.analysis_type === "sentry" && analysis.full_data && (() => {
          try {
            const data = JSON.parse(analysis.full_data);
            const patterns = data?.detected_patterns;
            if (!Array.isArray(patterns) || patterns.length === 0) return null;
            return (
              <div className="mt-4 flex flex-wrap items-center gap-2">
                <span className="text-xs text-gray-500 mr-1">Detected:</span>
                {patterns.map((p: { patternType: string; confidence: number; evidence: string[] }, i: number) => (
                  <span
                    key={i}
                    className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-lg text-xs font-medium border ${getPatternBadgeColor(p.patternType)}`}
                    title={p.evidence?.join("; ") || ""}
                  >
                    {getPatternLabel(p.patternType)}
                    <span className="opacity-60">{Math.round(p.confidence * 100)}%</span>
                  </span>
                ))}
              </div>
            );
          } catch { return null; }
        })()}

        {analysis.was_truncated && (
          <div className="mt-4 p-3 bg-yellow-500/10 border border-yellow-500/20 rounded-lg text-sm text-yellow-400">
            ⚠️ This file was truncated for analysis. Large portions may have been omitted.
          </div>
        )}
      </div>

      {/* Error Type */}
      <CollapsibleSection
        title="Error Type"
        icon={<AlertCircle className="w-5 h-5" />}
        badge={
          <span
            className={`px-3 py-1 rounded-lg text-xs font-semibold border ${getSeverityColor(
              analysis.severity
            )}`}
          >
            {analysis.severity.toUpperCase()}
          </span>
        }
      >
        <p className="text-gray-300 text-lg font-medium">{analysis.error_type}</p>

        {/* Error Message - if available */}
        {analysis.error_message && (
          <div className="mt-4 p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
            <div className="flex items-start gap-2">
              <AlertCircle className="w-4 h-4 text-red-400 mt-0.5 flex-shrink-0" />
              <p className="text-sm text-red-300">{analysis.error_message}</p>
            </div>
          </div>
        )}

        {/* Component - if available */}
        {analysis.component && (
          <div className="mt-3 flex items-center gap-2 text-sm">
            <Package className="w-4 h-4 text-blue-400" />
            <span className="text-gray-400">Affected Component:</span>
            <span className="text-blue-400 font-mono">{analysis.component}</span>
          </div>
        )}
      </CollapsibleSection>

      {/* Stack Trace - if available */}
      {analysis.stack_trace && (
        <CollapsibleSection
          title="Stack Trace"
          icon={<Activity className="w-5 h-5" />}
          defaultOpen={false}
        >
          <StackTraceViewer stackTrace={analysis.stack_trace} />
        </CollapsibleSection>
      )}

      {/* Root Cause - Multi-Part Analysis Viewer */}
      <MultiPartAnalysisViewer rootCause={analysis.root_cause} />

      {/* Suggested Fixes */}
      <CollapsibleSection
        title="Suggested Fixes"
        icon={<Wrench className="w-5 h-5" />}
        badge={
          Array.isArray(suggestedFixes) && (
            <span className="px-2 py-1 bg-blue-500/20 text-blue-400 rounded text-xs font-semibold">
              {suggestedFixes.length} {suggestedFixes.length === 1 ? 'Fix' : 'Fixes'}
            </span>
          )
        }
      >
        <div className="space-y-3">
          {Array.isArray(suggestedFixes) ? (
            suggestedFixes.map((fix, index) => (
              <div key={index} className="flex gap-3">
                <div className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center text-sm font-semibold">
                  {index + 1}
                </div>
                <p className="text-gray-300 flex-1">{fix}</p>
              </div>
            ))
          ) : (
            <div className="text-gray-300 whitespace-pre-wrap leading-relaxed">{suggestedFixes}</div>
          )}
        </div>
      </CollapsibleSection>

      {/* Metadata */}
      <CollapsibleSection
        title="Analysis Metadata"
        icon={<Info className="w-5 h-5" />}
        defaultOpen={false}
      >
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div>
            <span className="text-gray-400">Analysis ID:</span>
            <span className="ml-2 font-mono">{analysis.id}</span>
          </div>
          <div>
            <span className="text-gray-400">Tokens Used:</span>
            <span className="ml-2">{analysis.tokens_used.toLocaleString()}</span>
          </div>
          <div>
            <span className="text-gray-400">Model:</span>
            <span className="ml-2">{analysis.ai_model}</span>
          </div>
          {analysis.ai_provider && (
            <div>
              <span className="text-gray-400">Provider:</span>
              <span className="ml-2 capitalize">{analysis.ai_provider}</span>
            </div>
          )}
          {analysis.confidence && (
            <div>
              <span className="text-gray-400">Confidence:</span>
              <span className={`ml-2 font-semibold ${
                analysis.confidence === 'HIGH' ? 'text-green-400' :
                analysis.confidence === 'MEDIUM' ? 'text-yellow-400' :
                'text-orange-400'
              }`}>
                {analysis.confidence}
              </span>
            </div>
          )}
          <div>
            <span className="text-gray-400">Cost:</span>
            <span className="ml-2 text-green-400 font-semibold">${analysis.cost.toFixed(4)}</span>
          </div>
          {analysis.analysis_duration_ms && (
            <div>
              <span className="text-gray-400">Analysis Duration:</span>
              <span className="ml-2 text-blue-400 font-semibold">
                {(analysis.analysis_duration_ms / 1000).toFixed(2)}s
              </span>
            </div>
          )}
          <div>
            <span className="text-gray-400">File Size:</span>
            <span className="ml-2">{analysis.file_size_kb.toFixed(2)} KB</span>
          </div>
          <div>
            <span className="text-gray-400">Truncated:</span>
            <span className="ml-2">{analysis.was_truncated ? "Yes" : "No"}</span>
          </div>
          {analysis.is_favorite && (
            <div>
              <span className="text-gray-400">Favorite:</span>
              <span className="ml-2 text-yellow-400">★ Yes</span>
            </div>
          )}
          {analysis.view_count > 0 && (
            <div>
              <span className="text-gray-400">Views:</span>
              <span className="ml-2">{analysis.view_count}</span>
            </div>
          )}
          {analysis.analysis_mode && (
            <div>
              <span className="text-gray-400">Analysis Mode:</span>
              <span className={`ml-2 font-semibold ${
                analysis.analysis_mode === 'Deep Scan' ? 'text-purple-400' :
                analysis.analysis_mode?.includes('Extracted') ? 'text-amber-400' :
                'text-green-400'
              }`}>
                {analysis.analysis_mode}
              </span>
            </div>
          )}
          {analysis.token_utilization !== undefined && (
            <div>
              <span className="text-gray-400">Token Utilization:</span>
              <span className={`ml-2 font-semibold ${
                analysis.token_utilization > 80 ? 'text-orange-400' :
                analysis.token_utilization > 50 ? 'text-yellow-400' :
                'text-cyan-400'
              }`}>
                {analysis.token_utilization.toFixed(1)}%
              </span>
            </div>
          )}
          {analysis.coverage_summary && (
            <div className="col-span-2">
              <span className="text-gray-400">Coverage:</span>
              <span className="ml-2">{analysis.coverage_summary}</span>
            </div>
          )}
        </div>
      </CollapsibleSection>

      {/* Linked JIRA Tickets - Phase 3 */}
      {jiraEnabled && (
        <CollapsibleSection
          title="Linked JIRA Tickets"
          icon={<Link2 className="w-5 h-5" />}
          defaultOpen={true}
          headerContent={<JiraSyncStatus compact />}
        >
          <LinkedTickets analysisId={analysis.id} />
        </CollapsibleSection>
      )}

      {/* JIRA Ticket Modal */}
      <JiraTicketModal
        analysis={analysis}
        isOpen={showJiraModal}
        onClose={() => setShowJiraModal(false)}
      />

      {/* Export Dialog */}
      <ExportDialog
        analysis={analysis}
        isOpen={showExportDialog}
        onClose={() => setShowExportDialog(false)}
      />
    </div>
  );
}

// Sentry full_data parser
interface SentryFullData {
  issueId?: string;
  shortId?: string;
  permalink?: string;
  level?: string;
  status?: string;
  platform?: string;
  count?: string;
  userCount?: number;
}

function parseSentryFullData(fullData: string): SentryFullData | null {
  try {
    const data = JSON.parse(fullData);
    return {
      issueId: data.sentry_issue_id,
      shortId: data.sentry_short_id,
      permalink: data.sentry_permalink,
      level: data.sentry_level,
      status: data.sentry_status,
      platform: data.sentry_platform,
      count: data.sentry_count,
      userCount: data.sentry_user_count,
    };
  } catch {
    return null;
  }
}

// Pattern badge helpers for Sentry analysis
function getPatternBadgeColor(patternType: string): string {
  switch (patternType) {
    case "deadlock":
      return "bg-red-500/20 text-red-400 border-red-500/30";
    case "n_plus_one":
      return "bg-orange-500/20 text-orange-400 border-orange-500/30";
    case "memory_leak":
      return "bg-purple-500/20 text-purple-400 border-purple-500/30";
    case "unhandled_promise":
      return "bg-yellow-500/20 text-yellow-400 border-yellow-500/30";
    default:
      return "bg-gray-500/20 text-gray-400 border-gray-500/30";
  }
}

function getPatternLabel(patternType: string): string {
  switch (patternType) {
    case "deadlock":
      return "Deadlock";
    case "n_plus_one":
      return "N+1 Query";
    case "memory_leak":
      return "Memory Leak";
    case "unhandled_promise":
      return "Unhandled Promise";
    default:
      return patternType;
  }
}
