import { useState, useRef, useEffect } from "react";
import { format } from "date-fns";
import {
  ArrowLeft,
  Download,
  Copy,
  Check,
  AlertCircle,
  Lightbulb,
  Wrench,
  HelpCircle,
  Ticket,
  Zap,
} from "lucide-react";
import type { Analysis } from "../services/api";
import JiraTicketModal from "./JiraTicketModal";
import { isJiraEnabled } from "../services/jira";

interface QuickAnalysisDetailViewProps {
  analysis: Analysis;
  onBack: () => void;
}

interface QuickAnalysisData {
  rootCause: {
    title: string;
    technical: string;
    plainEnglish: string;
    affectedComponent: string;
  };
  workaround: {
    available: boolean;
    steps: string[];
    limitations: string;
  };
  solution: {
    summary: string;
    steps: string[];
    codeExample?: string;
    complexity: "Low" | "Medium" | "High";
  };
  explanation: {
    whyThisWorks: string;
    prevention: string;
  };
  severity: string;
  errorType: string;
}

function parseQuickAnalysis(fullData: string | null, rootCause: string): QuickAnalysisData | null {
  // Try parsing full_data as JSON first
  if (fullData) {
    try {
      const parsed = JSON.parse(fullData);
      if (parsed.rootCause && parsed.solution) {
        return parsed as QuickAnalysisData;
      }
    } catch {
      // Not JSON, continue to fallback
    }
  }

  // Fallback: Create structured data from root_cause text
  if (rootCause) {
    return {
      rootCause: {
        title: "Crash Analysis",
        technical: rootCause,
        plainEnglish: rootCause,
        affectedComponent: "Unknown",
      },
      workaround: {
        available: false,
        steps: [],
        limitations: "No workaround identified",
      },
      solution: {
        summary: "Review the root cause analysis for remediation steps",
        steps: [],
        complexity: "Medium",
      },
      explanation: {
        whyThisWorks: "Address the root cause to prevent recurrence",
        prevention: "Implement proper error handling and validation",
      },
      severity: "medium",
      errorType: "Unknown",
    };
  }

  return null;
}

function getSeverityColor(severity: string): string {
  switch (severity?.toLowerCase()) {
    case "critical":
      return "bg-red-500/10 border-red-500/30 text-red-400";
    case "high":
      return "bg-orange-500/10 border-orange-500/30 text-orange-400";
    case "medium":
      return "bg-yellow-500/10 border-yellow-500/30 text-yellow-400";
    case "low":
      return "bg-green-500/10 border-green-500/30 text-green-400";
    default:
      return "bg-gray-500/10 border-gray-500/30 text-gray-400";
  }
}

function getComplexityColor(complexity: string): string {
  switch (complexity) {
    case "Low":
      return "text-green-400 bg-green-500/20";
    case "Medium":
      return "text-yellow-400 bg-yellow-500/20";
    case "High":
      return "text-red-400 bg-red-500/20";
    default:
      return "text-gray-400 bg-gray-500/20";
  }
}

export default function QuickAnalysisDetailView({ analysis, onBack }: QuickAnalysisDetailViewProps) {
  const [copied, setCopied] = useState(false);
  const [showJiraModal, setShowJiraModal] = useState(false);
  const [jiraEnabled, setJiraEnabled] = useState(false);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Parse the quick analysis data
  const quickData = parseQuickAnalysis(analysis.full_data ?? null, analysis.root_cause);

  // Check if JIRA is enabled
  useEffect(() => {
    isJiraEnabled().then(setJiraEnabled);
  }, []);

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
  }, []);

  const handleCopyToClipboard = () => {
    const text = quickData
      ? `
Quick Crash Analysis Report - ${analysis.filename}
===================================================

ROOT CAUSE
----------
${quickData.rootCause.technical}

${quickData.workaround.available ? `WORKAROUND
----------
${quickData.workaround.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}
` : ""}
SOLUTION
--------
${quickData.solution.summary}
${quickData.solution.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

WHY THIS WORKS
--------------
${quickData.explanation.whyThisWorks}

---
Generated by Hadron - Quick Crash Analyzer
      `.trim()
      : `
Quick Analysis Report - ${analysis.filename}
============================================

${analysis.root_cause}

---
Generated by Hadron - Quick Crash Analyzer
      `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => setCopied(false), 2000);
  };

  const handleExportMarkdown = () => {
    const markdown = quickData
      ? `# Quick Crash Analysis: ${analysis.filename}

## Summary
- **Severity:** ${analysis.severity.toUpperCase()}
- **Error Type:** ${analysis.error_type}
- **Analyzed:** ${format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}
- **Cost:** $${analysis.cost.toFixed(4)}

## Root Cause

### Technical
${quickData.rootCause.technical}

### Plain English
${quickData.rootCause.plainEnglish}

**Affected Component:** ${quickData.rootCause.affectedComponent}

${quickData.workaround.available ? `## Workaround
${quickData.workaround.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

**Limitations:** ${quickData.workaround.limitations}
` : ""}
## Solution
**${quickData.solution.summary}**

**Complexity:** ${quickData.solution.complexity}

${quickData.solution.steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

${quickData.solution.codeExample ? `### Code Example
\`\`\`
${quickData.solution.codeExample}
\`\`\`
` : ""}
## Why This Fix Works
${quickData.explanation.whyThisWorks}

### Prevention
${quickData.explanation.prevention}

---
*Generated by Hadron - Quick Crash Analyzer*
`
      : `# Quick Analysis: ${analysis.filename}

**Severity:** ${analysis.severity.toUpperCase()}
**Analyzed:** ${format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}

## Analysis
${analysis.root_cause}

---
*Generated by Hadron - Quick Crash Analyzer*
`;

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${analysis.filename.replace(/\.(txt|log)$/i, "")}-quick-analysis.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Use analysis data even without enhanced parsing
  const displayData = quickData || {
    rootCause: {
      title: analysis.error_type || "Crash Analysis",
      technical: analysis.root_cause,
      plainEnglish: analysis.root_cause,
      affectedComponent: "See analysis details",
    },
    workaround: {
      available: false,
      steps: [],
      limitations: "",
    },
    solution: {
      summary: "Review the analysis for recommended fixes",
      steps: analysis.suggested_fixes ? JSON.parse(analysis.suggested_fixes) as string[] : [],
      codeExample: undefined as string | undefined,
      complexity: "Medium" as const,
    },
    explanation: {
      whyThisWorks: "Addressing the root cause prevents recurrence",
      prevention: "Implement proper error handling",
    },
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <button
          onClick={onBack}
          className="flex items-center gap-2 px-4 py-2 hover:bg-gray-700 rounded-lg transition"
        >
          <ArrowLeft className="w-5 h-5" />
          Back to History
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyToClipboard}
            className="flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg transition"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-green-400" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy Report
              </>
            )}
          </button>
          <button
            onClick={handleExportMarkdown}
            className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg transition"
          >
            <Download className="w-4 h-4" />
            Export
          </button>
          {jiraEnabled && (
            <button
              onClick={() => setShowJiraModal(true)}
              className="flex items-center gap-2 px-4 py-2 bg-green-600 hover:bg-green-700 rounded-lg transition"
              title="Create JIRA ticket from this analysis"
            >
              <Ticket className="w-4 h-4" />
              Create JIRA Ticket
            </button>
          )}
        </div>
      </div>

      {/* File Info Card */}
      <div className="bg-gray-800 border border-gray-700 rounded-lg p-6">
        <div className="flex items-start justify-between mb-4">
          <div className="flex-1">
            <div className="flex items-center gap-3 mb-2">
              <Zap className="w-6 h-6 text-cyan-400" />
              <h2 className="text-2xl font-bold">Quick Analysis</h2>
            </div>
            <p className="text-gray-400 text-sm mb-3">{analysis.filename}</p>
            <div className="flex items-center gap-3 text-sm text-gray-400 flex-wrap">
              <span>{format(new Date(analysis.analyzed_at), "MMMM d, yyyy 'at' h:mm a")}</span>
              <span>|</span>
              <span>{analysis.ai_model}</span>
              <span>|</span>
              <span className="text-green-400">${analysis.cost.toFixed(4)}</span>
            </div>
          </div>
          <span
            className={`px-4 py-2 rounded-lg text-sm font-semibold border ${getSeverityColor(
              analysis.severity
            )}`}
          >
            {analysis.severity.toUpperCase()}
          </span>
        </div>
      </div>

      {/* Main Content - 4 Sections */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Root Cause */}
        <div className="bg-gray-800 border border-gray-700 rounded-lg p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-red-500/20 rounded-lg">
              <AlertCircle className="w-5 h-5 text-red-400" />
            </div>
            <h3 className="text-lg font-semibold">Root Cause</h3>
          </div>

          <div className="space-y-4">
            <div>
              <h4 className="text-sm font-semibold text-gray-400 mb-2">What Happened</h4>
              <p className="text-gray-200">{displayData.rootCause.technical}</p>
            </div>

            <div className="p-4 bg-blue-500/10 border border-blue-500/20 rounded-lg">
              <h4 className="text-sm font-semibold text-blue-400 mb-2">In Simple Terms</h4>
              <p className="text-gray-200">{displayData.rootCause.plainEnglish}</p>
            </div>

            <div className="text-sm">
              <span className="text-gray-400">Affected Component: </span>
              <code className="px-2 py-1 bg-gray-900 rounded text-cyan-400">
                {displayData.rootCause.affectedComponent}
              </code>
            </div>
          </div>
        </div>

        {/* Workaround */}
        <div className="bg-gray-800 border border-gray-700 rounded-lg p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-yellow-500/20 rounded-lg">
              <Lightbulb className="w-5 h-5 text-yellow-400" />
            </div>
            <h3 className="text-lg font-semibold">Workaround</h3>
          </div>

          {displayData.workaround.available && displayData.workaround.steps.length > 0 ? (
            <div className="space-y-4">
              <p className="text-sm text-gray-400">Temporary steps to avoid this issue:</p>
              <ol className="space-y-2">
                {displayData.workaround.steps.map((step, index) => (
                  <li key={index} className="flex gap-3">
                    <div className="flex-shrink-0 w-6 h-6 rounded-full bg-yellow-500/20 text-yellow-400 flex items-center justify-center text-sm font-semibold">
                      {index + 1}
                    </div>
                    <span className="text-gray-200">{step}</span>
                  </li>
                ))}
              </ol>
              {displayData.workaround.limitations && (
                <div className="p-3 bg-yellow-500/10 border border-yellow-500/20 rounded-lg">
                  <span className="text-sm text-yellow-400 font-semibold">Note: </span>
                  <span className="text-sm text-gray-300">{displayData.workaround.limitations}</span>
                </div>
              )}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-8 text-gray-500">
              <Lightbulb className="w-12 h-12 mb-3 opacity-30" />
              <p className="text-sm">No temporary workaround available</p>
              <p className="text-xs mt-1">Proceed directly to the solution</p>
            </div>
          )}
        </div>

        {/* Solution */}
        <div className="bg-gray-800 border border-gray-700 rounded-lg p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-green-500/20 rounded-lg">
              <Wrench className="w-5 h-5 text-green-400" />
            </div>
            <h3 className="text-lg font-semibold">Solution</h3>
            <span className={`ml-auto px-2 py-1 rounded text-xs font-medium ${getComplexityColor(displayData.solution.complexity)}`}>
              {displayData.solution.complexity} Complexity
            </span>
          </div>

          <div className="space-y-4">
            <div className="p-4 bg-green-500/10 border border-green-500/20 rounded-lg">
              <p className="text-green-300 font-medium">{displayData.solution.summary}</p>
            </div>

            {displayData.solution.steps.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold text-gray-400 mb-3">Implementation Steps</h4>
                <ol className="space-y-2">
                  {displayData.solution.steps.map((step, index) => (
                    <li key={index} className="flex gap-3">
                      <div className="flex-shrink-0 w-6 h-6 rounded-full bg-green-500/20 text-green-400 flex items-center justify-center text-sm font-semibold">
                        {index + 1}
                      </div>
                      <span className="text-gray-200">{step}</span>
                    </li>
                  ))}
                </ol>
              </div>
            )}

            {displayData.solution.codeExample && (
              <div>
                <h4 className="text-sm font-semibold text-gray-400 mb-2">Code Example</h4>
                <pre className="p-4 bg-gray-900 rounded-lg overflow-x-auto text-sm font-mono text-gray-300">
                  {displayData.solution.codeExample}
                </pre>
              </div>
            )}
          </div>
        </div>

        {/* Why This Fix Works */}
        <div className="bg-gray-800 border border-gray-700 rounded-lg p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-purple-500/20 rounded-lg">
              <HelpCircle className="w-5 h-5 text-purple-400" />
            </div>
            <h3 className="text-lg font-semibold">Why This Fix Works</h3>
          </div>

          <div className="space-y-4">
            <div>
              <h4 className="text-sm font-semibold text-gray-400 mb-2">Explanation</h4>
              <p className="text-gray-200">{displayData.explanation.whyThisWorks}</p>
            </div>

            <div className="p-4 bg-purple-500/10 border border-purple-500/20 rounded-lg">
              <h4 className="text-sm font-semibold text-purple-400 mb-2">Prevention</h4>
              <p className="text-gray-300">{displayData.explanation.prevention}</p>
            </div>
          </div>
        </div>
      </div>

      {/* JIRA Ticket Modal */}
      <JiraTicketModal
        analysis={analysis}
        isOpen={showJiraModal}
        onClose={() => setShowJiraModal(false)}
      />
    </div>
  );
}
