import { useState } from "react";
import type { Analysis } from "../../services/api";
import type { WhatsOnEnhancedAnalysis } from "../../types";
import CopyBtn from "../ui/CopyBtn";
import Tag from "../ui/Tag";

interface ExportDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: Analysis;
  enhancedData: WhatsOnEnhancedAnalysis;
  onExportMarkdown: () => void;
  onExportDocx: () => void;
  isExportingDocx?: boolean;
}

function developerBrief(a: Analysis, ed: WhatsOnEnhancedAnalysis) {
  const frames = ed.stackTrace?.frames
    .map(f => `[${f.index}] [${f.type.toUpperCase()}] ${f.method}${f.context ? `\n    → ${f.context}` : ""}`)
    .join("\n") ?? "Not available";
  const p0 = ed.suggestedFix.codeChanges.filter(c => c.priority === "P0");
  return `# Developer Brief — ${a.filename}
Severity: ${a.severity} | Component: ${a.component ?? "Unknown"}

## Root Cause
${ed.rootCause.technical}

Affected: ${ed.rootCause.affectedMethod} (${ed.rootCause.affectedModule})
${ed.rootCause.triggerCondition ? `Trigger: ${ed.rootCause.triggerCondition}` : ""}

## Stack Trace
${frames}

## P0 Fix
${p0.map(c => `### ${c.file}\n${c.description}${c.before ? `\n\nBefore:\n${c.before}` : ""}${c.after ? `\n\nAfter:\n${c.after}` : ""}`).join("\n\n") || ed.suggestedFix.summary}

---
_Generated by Hadron_`;
}

function supportSummary(a: Analysis, ed: WhatsOnEnhancedAnalysis) {
  return `# Support Summary — ${a.filename}
Severity: ${a.severity}

## Verdict
${ed.summary.title}

## Root Cause (Plain English)
${ed.rootCause.plainEnglish}

## User Journey
${ed.userScenario.steps.map(s => `${s.step}. ${s.action}${s.isCrashPoint ? " [CRASH POINT]" : ""}`).join("\n")}

Expected: ${ed.userScenario.expectedResult}
Actual: ${ed.userScenario.actualResult}

## Fix
${ed.suggestedFix.summary}
Effort: ${ed.suggestedFix.estimatedEffort} | Risk: ${ed.suggestedFix.riskLevel} | Complexity: ${ed.suggestedFix.complexity}

---
_Generated by Hadron_`;
}

function customerReply(a: Analysis, ed: WhatsOnEnhancedAnalysis) {
  return `Dear Customer,

Thank you for reporting this issue.

SUMMARY
The application encountered an error while ${ed.summary.affectedWorkflow?.toLowerCase() ?? "performing the requested operation"}. Our engineers have investigated and identified the cause.

CAUSE
${ed.rootCause.plainEnglish}

WORKAROUND
Until the fix is deployed, please avoid the workflow that triggered this error. Contact support if you need immediate assistance.

RESOLUTION
Our development team has identified a fix (estimated effort: ${ed.suggestedFix.estimatedEffort}). You will be notified once it is available.

Kind regards,
Support Team`;
}

function jiraTicket(a: Analysis, ed: WhatsOnEnhancedAnalysis) {
  return `**${a.filename}** | ${a.severity} | ${ed.summary.category}

## Summary
${ed.summary.title}

## Root Cause
${ed.rootCause.technical}

Affected method: \`${ed.rootCause.affectedMethod}\`
Module: ${ed.rootCause.affectedModule}
${ed.rootCause.triggerCondition ? `Trigger: ${ed.rootCause.triggerCondition}` : ""}

## Reproduction Steps
${ed.userScenario.steps.map(s => `${s.step}. ${s.action}`).join("\n")}

**Expected:** ${ed.userScenario.expectedResult}
**Actual:** ${ed.userScenario.actualResult}

## Suggested Fix
${ed.suggestedFix.summary}
- Complexity: ${ed.suggestedFix.complexity}
- Effort: ${ed.suggestedFix.estimatedEffort}
- Risk: ${ed.suggestedFix.riskLevel}

---
_Generated by Hadron_`;
}

export default function ExportDrawer({ isOpen, onClose, analysis, enhancedData, onExportMarkdown, onExportDocx, isExportingDocx }: ExportDrawerProps) {
  const [preview, setPreview] = useState<string | null>(null);
  const mono = "var(--hd-font-mono,'JetBrains Mono',monospace)";

  const formats = [
    { id: "dev",  label: "Developer Brief",  tag: "MD",  desc: "Stack, root cause, P0 fix",      gen: () => developerBrief(analysis, enhancedData), accent: "#3b82f6" },
    { id: "sup",  label: "Support Summary",  tag: "MD",  desc: "Verdict, journey, fix handoff",  gen: () => supportSummary(analysis, enhancedData), accent: "#8b5cf6" },
    { id: "cust", label: "Customer Reply",   tag: "TXT", desc: "Ready-to-send email template",   gen: () => customerReply(analysis, enhancedData), accent: "#10b981" },
    { id: "jira", label: "JIRA Ticket",      tag: "MD",  desc: "Structured bug report",          gen: () => jiraTicket(analysis, enhancedData), accent: "#f59e0b" },
  ];

  const pvItem = preview ? formats.find(f => f.id === preview) : null;

  if (!isOpen) return null;

  return (
    <>
      <div onClick={onClose} style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", zIndex: 200, backdropFilter: "blur(2px)" }} />
      <div style={{
        position: "fixed", right: 0, top: 0, bottom: 0,
        width: pvItem ? "700px" : "370px",
        background: "var(--hd-bg-raised,#111114)",
        borderLeft: "1px solid rgba(255,255,255,0.08)",
        zIndex: 201,
        display: "flex", flexDirection: "column",
        transition: "width .25s ease",
        boxShadow: "-20px 0 60px rgba(0,0,0,0.4)",
      }}>
        {/* Header */}
        <div style={{ padding: "14px 18px", borderBottom: "1px solid rgba(255,255,255,0.06)", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div>
            <div style={{ color: "#e5e7eb", fontSize: "14px", fontWeight: 600 }}>Export Analysis</div>
            <div style={{ color: "#6b7280", fontSize: "11px", fontFamily: mono }}>{analysis.filename}</div>
          </div>
          <button onClick={onClose} style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", color: "#9ca3af", width: "26px", height: "26px", borderRadius: "5px", cursor: "pointer", fontSize: "13px" }}>×</button>
        </div>

        <div style={{ display: "flex", flex: 1, overflow: "hidden" }}>
          {/* Format list */}
          <div style={{ flex: pvItem ? "0 0 370px" : 1, overflowY: "auto", padding: "14px 18px" }}>
            <div style={{ color: "#6b7280", fontSize: "10px", fontWeight: 700, letterSpacing: ".1em", fontFamily: mono, marginBottom: "8px" }}>⎘ COPY TO CLIPBOARD</div>

            {formats.map(f => {
              const isPv = preview === f.id;
              return (
                <div key={f.id} style={{
                  background: isPv ? "rgba(255,255,255,0.04)" : "rgba(255,255,255,0.02)",
                  border: `1px solid ${isPv ? "rgba(255,255,255,0.1)" : "rgba(255,255,255,0.04)"}`,
                  borderRadius: "7px", padding: "10px", marginBottom: "4px",
                }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
                    <span style={{ color: "#e5e7eb", fontSize: "12px", fontWeight: 600 }}>{f.label}</span>
                    <Tag text={f.tag} color={f.accent} />
                  </div>
                  <div style={{ color: "#6b7280", fontSize: "11px", marginTop: "3px" }}>{f.desc}</div>
                  <div style={{ display: "flex", gap: "5px", marginTop: "8px" }}>
                    <CopyBtn text={f.gen()} />
                    <button
                      onClick={() => setPreview(isPv ? null : f.id)}
                      style={{ background: isPv ? "rgba(255,255,255,0.08)" : "transparent", border: `1px solid ${isPv ? "rgba(255,255,255,0.12)" : "rgba(255,255,255,0.06)"}`, color: isPv ? "#d1d5db" : "#6b7280", padding: "4px 10px", borderRadius: "4px", fontSize: "11px", cursor: "pointer", fontFamily: mono }}
                    >
                      {isPv ? "Hide" : "Preview"}
                    </button>
                  </div>
                </div>
              );
            })}

            <div style={{ color: "#6b7280", fontSize: "10px", fontWeight: 700, letterSpacing: ".1em", fontFamily: mono, marginTop: "14px", marginBottom: "8px" }}>↓ DOWNLOAD</div>
            <button
              onClick={onExportMarkdown}
              style={{ width: "100%", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "6px", padding: "9px 12px", color: "#9ca3af", fontSize: "12px", cursor: "pointer", fontFamily: mono, textAlign: "left", marginBottom: "4px" }}
            >
              ↓ Analysis Report (.md)
            </button>
            <button
              onClick={onExportDocx}
              disabled={isExportingDocx}
              style={{ width: "100%", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: "6px", padding: "9px 12px", color: isExportingDocx ? "#4b5563" : "#9ca3af", fontSize: "12px", cursor: isExportingDocx ? "default" : "pointer", fontFamily: mono, textAlign: "left" }}
            >
              {isExportingDocx ? "Exporting…" : "↓ Annotated WCR (.docx)"}
            </button>
          </div>

          {/* Preview pane */}
          {pvItem && (
            <div style={{ flex: 1, borderLeft: "1px solid rgba(255,255,255,0.06)", display: "flex", flexDirection: "column", overflow: "hidden" }}>
              <div style={{ padding: "10px 14px", borderBottom: "1px solid rgba(255,255,255,0.06)", display: "flex", justifyContent: "space-between", alignItems: "center", flexShrink: 0 }}>
                <span style={{ color: "#e5e7eb", fontSize: "12px", fontWeight: 600 }}>{pvItem.label}</span>
                <CopyBtn text={pvItem.gen()} />
              </div>
              <div style={{ flex: 1, overflow: "auto", padding: "14px" }}>
                <pre style={{ fontFamily: mono, fontSize: "11px", color: "#9ca3af", lineHeight: 1.7, whiteSpace: "pre-wrap", margin: 0 }}>{pvItem.gen()}</pre>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
