//! Basic CRUD operations for analyses and translations

use crate::database::{Analysis, Translation};
use crate::error::CommandResult;
use super::common::DbState;
use std::sync::Arc;

/// Get all analyses from history (with default pagination)
#[tauri::command]
pub async fn get_all_analyses(db: DbState<'_>) -> CommandResult<Vec<Analysis>> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_all_analyses()).await??)
}

/// Get analyses with pagination
/// - limit: Number of results to return (-1 for unlimited)
/// - offset: Number of results to skip
#[tauri::command]
pub async fn get_analyses_paginated(
    limit: Option<i64>,
    offset: Option<i64>,
    db: DbState<'_>,
) -> CommandResult<Vec<Analysis>> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_analyses_paginated(limit, offset)).await??)
}

/// Get total count of analyses (for pagination UI)
#[tauri::command]
pub async fn get_analyses_count(db: DbState<'_>) -> CommandResult<i64> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_analyses_count()).await??)
}

/// Get a specific analysis by ID
#[tauri::command]
pub async fn get_analysis_by_id(id: i64, db: DbState<'_>) -> CommandResult<Analysis> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_analysis_by_id(id)).await??)
}

/// Delete an analysis
#[tauri::command]
pub async fn delete_analysis(id: i64, db: DbState<'_>) -> CommandResult<()> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.delete_analysis(id)).await??)
}

/// Export analysis to Markdown
#[tauri::command]
pub async fn export_analysis(id: i64, db: DbState<'_>) -> CommandResult<String> {
    let db = Arc::clone(&db);
    let analysis = tauri::async_runtime::spawn_blocking(move || db.get_analysis_by_id(id)).await??;

    let fixes: Vec<String> = serde_json::from_str(&analysis.suggested_fixes).unwrap_or_else(|e| {
        log::warn!(
            "Failed to deserialize suggested_fixes for analysis {}: {}",
            id,
            e
        );
        vec!["(Unable to parse suggested fixes)".to_string()]
    });

    let markdown = format!(
        "# Crash Analysis Report\n\n\
         **File**: {}\n\
         **Error Type**: {}\n\
         **Severity**: {}\n\
         **Analyzed**: {}\n\n\
         ## Root Cause\n\n{}\n\n\
         ## Suggested Fixes\n\n{}\n\n\
         ---\n\
         Generated by Hadron - AI Support Assistant\n",
        analysis.filename,
        analysis.error_type,
        analysis.severity,
        analysis.analyzed_at,
        analysis.root_cause,
        fixes
            .iter()
            .enumerate()
            .map(|(i, fix)| format!("{}. {}", i + 1, fix))
            .collect::<Vec<_>>()
            .join("\n")
    );

    Ok(markdown)
}

/// Toggle favorite status for an analysis
#[tauri::command]
pub async fn toggle_favorite(id: i64, db: DbState<'_>) -> CommandResult<bool> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.toggle_favorite(id)).await??)
}

/// Get all favorite analyses
#[tauri::command]
pub async fn get_favorites(db: DbState<'_>) -> CommandResult<Vec<Analysis>> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_favorites()).await??)
}

/// Get recently viewed analyses
#[tauri::command]
pub async fn get_recent(limit: Option<i64>, db: DbState<'_>) -> CommandResult<Vec<Analysis>> {
    let db = Arc::clone(&db);
    let limit = limit.unwrap_or(10);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_recent(limit)).await??)
}

/// Get database statistics
#[tauri::command]
pub async fn get_database_statistics(db: DbState<'_>) -> CommandResult<serde_json::Value> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_statistics()).await??)
}

/// Optimize FTS5 index
#[tauri::command]
pub async fn optimize_fts_index(db: DbState<'_>) -> CommandResult<()> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.optimize_fts()).await??)
}

/// Run database integrity check
#[tauri::command]
pub async fn check_database_integrity(db: DbState<'_>) -> CommandResult<bool> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.integrity_check()).await??)
}

/// Compact database (VACUUM)
#[tauri::command]
pub async fn compact_database(db: DbState<'_>) -> CommandResult<()> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.compact()).await??)
}

/// Checkpoint WAL file
#[tauri::command]
pub async fn checkpoint_wal(db: DbState<'_>) -> CommandResult<()> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.checkpoint_wal()).await??)
}

/// Get all translations
#[tauri::command]
pub async fn get_all_translations(db: DbState<'_>) -> CommandResult<Vec<Translation>> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_all_translations()).await??)
}

/// Get translation by ID
#[tauri::command]
pub async fn get_translation_by_id(id: i64, db: DbState<'_>) -> CommandResult<Translation> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.get_translation_by_id(id)).await??)
}

/// Delete a translation
#[tauri::command]
pub async fn delete_translation(id: i64, db: DbState<'_>) -> CommandResult<()> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.delete_translation(id)).await??)
}

/// Toggle favorite status for a translation
#[tauri::command]
pub async fn toggle_translation_favorite(id: i64, db: DbState<'_>) -> CommandResult<bool> {
    let db = Arc::clone(&db);
    Ok(tauri::async_runtime::spawn_blocking(move || db.toggle_translation_favorite(id)).await??)
}
