//! Basic CRUD operations for analyses and translations

use crate::database::{Analysis, Translation};
use super::common::DbState;
use std::sync::Arc;

/// Get all analyses from history (with default pagination)
#[tauri::command]
pub async fn get_all_analyses(db: DbState<'_>) -> Result<Vec<Analysis>, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.get_all_analyses())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Get analyses with pagination
/// - limit: Number of results to return (-1 for unlimited)
/// - offset: Number of results to skip
#[tauri::command]
pub async fn get_analyses_paginated(
    limit: Option<i64>,
    offset: Option<i64>,
    db: DbState<'_>,
) -> Result<Vec<Analysis>, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.get_analyses_paginated(limit, offset))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Get total count of analyses (for pagination UI)
#[tauri::command]
pub async fn get_analyses_count(db: DbState<'_>) -> Result<i64, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.get_analyses_count())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Get a specific analysis by ID
#[tauri::command]
pub async fn get_analysis_by_id(id: i64, db: DbState<'_>) -> Result<Analysis, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.get_analysis_by_id(id))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Delete an analysis
#[tauri::command]
pub async fn delete_analysis(id: i64, db: DbState<'_>) -> Result<(), String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.delete_analysis(id))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Export analysis to Markdown
#[tauri::command]
pub async fn export_analysis(id: i64, db: DbState<'_>) -> Result<String, String> {
    let db = Arc::clone(&db);
    let analysis = tauri::async_runtime::spawn_blocking(move || db.get_analysis_by_id(id))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))?;

    let fixes: Vec<String> = serde_json::from_str(&analysis.suggested_fixes).unwrap_or_else(|e| {
        log::warn!(
            "Failed to deserialize suggested_fixes for analysis {}: {}",
            id,
            e
        );
        vec!["(Unable to parse suggested fixes)".to_string()]
    });

    let markdown = format!(
        "# Crash Analysis Report\n\n\
         **File**: {}\n\
         **Error Type**: {}\n\
         **Severity**: {}\n\
         **Analyzed**: {}\n\n\
         ## Root Cause\n\n{}\n\n\
         ## Suggested Fixes\n\n{}\n\n\
         ---\n\
         Generated by Hadron - Smalltalk Crash Analyzer\n",
        analysis.filename,
        analysis.error_type,
        analysis.severity,
        analysis.analyzed_at,
        analysis.root_cause,
        fixes
            .iter()
            .enumerate()
            .map(|(i, fix)| format!("{}. {}", i + 1, fix))
            .collect::<Vec<_>>()
            .join("\n")
    );

    Ok(markdown)
}

/// Toggle favorite status for an analysis
#[tauri::command]
pub async fn toggle_favorite(id: i64, db: DbState<'_>) -> Result<bool, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.toggle_favorite(id))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Get all favorite analyses
#[tauri::command]
pub async fn get_favorites(db: DbState<'_>) -> Result<Vec<Analysis>, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.get_favorites())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Get recently viewed analyses
#[tauri::command]
pub async fn get_recent(limit: Option<i64>, db: DbState<'_>) -> Result<Vec<Analysis>, String> {
    let db = Arc::clone(&db);
    let limit = limit.unwrap_or(10);
    tauri::async_runtime::spawn_blocking(move || db.get_recent(limit))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Get database statistics
#[tauri::command]
pub async fn get_database_statistics(db: DbState<'_>) -> Result<serde_json::Value, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.get_statistics())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Optimize FTS5 index
#[tauri::command]
pub async fn optimize_fts_index(db: DbState<'_>) -> Result<(), String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.optimize_fts())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Run database integrity check
#[tauri::command]
pub async fn check_database_integrity(db: DbState<'_>) -> Result<bool, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.integrity_check())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Compact database (VACUUM)
#[tauri::command]
pub async fn compact_database(db: DbState<'_>) -> Result<(), String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.compact())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Checkpoint WAL file
#[tauri::command]
pub async fn checkpoint_wal(db: DbState<'_>) -> Result<(), String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.checkpoint_wal())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Get all translations
#[tauri::command]
pub async fn get_all_translations(db: DbState<'_>) -> Result<Vec<Translation>, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.get_all_translations())
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Get translation by ID
#[tauri::command]
pub async fn get_translation_by_id(id: i64, db: DbState<'_>) -> Result<Translation, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.get_translation_by_id(id))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Delete a translation
#[tauri::command]
pub async fn delete_translation(id: i64, db: DbState<'_>) -> Result<(), String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.delete_translation(id))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}

/// Toggle favorite status for a translation
#[tauri::command]
pub async fn toggle_translation_favorite(id: i64, db: DbState<'_>) -> Result<bool, String> {
    let db = Arc::clone(&db);
    tauri::async_runtime::spawn_blocking(move || db.toggle_translation_favorite(id))
        .await
        .map_err(|e| format!("Task error: {}", e))?
        .map_err(|e| format!("Database error: {}", e))
}
