import { useState, useEffect, useRef } from "react";
import { invoke } from "../lib/tauri-core-shim";
import { format } from "date-fns";
import logger from "../services/logger";
import { AlertTriangle, Loader2 } from "lucide-react";
import type { Analysis } from "../services/api";
import { parseWhatsOnAnalysis } from "../utils/whatsOnParser";
import JiraTicketModal from "./JiraTicketModal";
import { isJiraEnabled } from "../services/jira";
import { GoldBadge } from "./GoldBadge";
import { generateAnnotatedWcrDocx } from "../utils/generateAnnotatedWcrDocx";

import SupportTab from "./whatson/SupportTab";
import DeveloperTab from "./whatson/DeveloperTab";
import CustomerTab from "./whatson/CustomerTab";
import ExecutiveTab from "./whatson/ExecutiveTab";
import ExportDrawer from "./whatson/ExportDrawer";

interface WhatsOnDetailViewProps {
  analysis: Analysis;
  onBack: () => void;
}

type TabId = "support" | "developer" | "customer" | "executive";

const TABS: { id: TabId; label: string; icon: string }[] = [
  { id: "support",   label: "Support Engineer", icon: "◎" },
  { id: "developer", label: "Developer",        icon: "⌘" },
  { id: "customer",  label: "Customer-Facing",  icon: "✉" },
  { id: "executive", label: "Executive",        icon: "◈" },
];

const SEV_COLOR: Record<string, string> = {
  critical: "#ef4444",
  high:     "#f59e0b",
  medium:   "#3b82f6",
  low:      "#10b981",
};

function getSevColor(s: string) {
  return SEV_COLOR[s?.toLowerCase()] ?? "#6b7280";
}

export default function WhatsOnDetailView({ analysis, onBack }: WhatsOnDetailViewProps) {
  const [tab, setTab] = useState<TabId>("support");
  const [expanded, setExpanded] = useState(false);
  const [showExport, setShowExport] = useState(false);
  const [showJira, setShowJira] = useState(false);
  const [jiraEnabled, setJiraEnabled] = useState(false);
  const [isGold, setIsGold] = useState(false);
  const [editableRootCause, setEditableRootCause] = useState<string | null>(null);
  const [isExportingDocx, setIsExportingDocx] = useState(false);
  const timeoutRef = useRef<NodeJS.Timeout | null>(null);

  const mono = "var(--hd-font-mono,'JetBrains Mono',monospace)";
  const sans = "var(--hd-font-sans,'IBM Plex Sans',system-ui,sans-serif)";

  const enhancedData = parseWhatsOnAnalysis(analysis.full_data, analysis.root_cause);
  const currentRootCause = editableRootCause ?? enhancedData?.rootCause?.technical ?? "";

  useEffect(() => { isJiraEnabled().then(setJiraEnabled); }, []);

  useEffect(() => {
    invoke<boolean>("is_gold_analysis", { analysisId: analysis.id })
      .then(setIsGold)
      .catch(err => logger.error("Failed to check gold status", { error: String(err) }));
  }, [analysis.id]);

  useEffect(() => () => { if (timeoutRef.current) clearTimeout(timeoutRef.current); }, []);

  const handleExportDocx = async () => {
    if (!enhancedData) return;
    setIsExportingDocx(true);
    try {
      const blob = await generateAnnotatedWcrDocx(enhancedData, analysis);
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${analysis.filename.replace(/\.(txt|log)$/i, "")}-annotated-wcr.docx`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      logger.error("Annotated WCR export failed", { error: String(err) });
    } finally {
      setIsExportingDocx(false);
    }
  };

  const handleExportMarkdown = () => {
    if (!enhancedData) return;
    const md = `# WHATS'ON Crash Analysis: ${analysis.filename}

## Summary
- **Title:** ${enhancedData.summary.title}
- **Severity:** ${enhancedData.summary.severity.toUpperCase()}
- **Category:** ${enhancedData.summary.category}
- **Confidence:** ${enhancedData.summary.confidence}
- **Affected Workflow:** ${enhancedData.summary.affectedWorkflow ?? "N/A"}

## Root Cause

### Technical
${enhancedData.rootCause.technical}

### Plain English
${enhancedData.rootCause.plainEnglish}

- **Affected Method:** \`${enhancedData.rootCause.affectedMethod}\`
- **Affected Module:** ${enhancedData.rootCause.affectedModule}

## Suggested Fix
**${enhancedData.suggestedFix.summary}**

${enhancedData.suggestedFix.reasoning}

${enhancedData.suggestedFix.codeChanges.map(c =>
  `### ${c.file} (${c.priority})\n${c.description}${c.before ? `\n\n**Before:**\n\`\`\`\n${c.before}\n\`\`\`` : ""}${c.after ? `\n\n**After:**\n\`\`\`\n${c.after}\n\`\`\`` : ""}`
).join("\n\n")}

## User Scenario
${enhancedData.userScenario.steps.map(s => `${s.step}. ${s.action}${s.isCrashPoint ? " **[CRASH]**" : ""}`).join("\n")}

---
*Generated by Hadron · WHATS'ON Crash Analyzer*`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${analysis.filename.replace(/\.(txt|log)$/i, "")}-analysis.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // ── Fallback view ──────────────────────────────────────────────────────────
  if (!enhancedData) {
    logger.debug("WhatsOnDetailView: enhanced data not available", {
      analysisType: analysis.analysis_type,
      hasFullData: !!analysis.full_data,
      fullDataLength: analysis.full_data?.length ?? 0,
    });
    return (
      <div className="space-y-6">
        <nav className="flex items-center gap-1.5 text-sm">
          <button onClick={onBack} className="flex items-center gap-1.5 text-gray-400 hover:text-white transition">
            ◀ History
          </button>
          <span className="text-gray-600">/</span>
          <span className="text-gray-400 truncate max-w-xs">{analysis.filename}</span>
        </nav>
        <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-6">
          <div className="flex items-center gap-3 mb-4">
            <AlertTriangle className="w-6 h-6 text-yellow-400" />
            <h2 className="text-xl font-bold text-yellow-400">Enhanced Data Not Available</h2>
          </div>
          <p className="text-gray-300 mb-2">This analysis does not contain WHATS'ON enhanced data.</p>
          <ul className="list-disc list-inside text-gray-400 space-y-1 text-sm">
            <li>Analysis type: {analysis.analysis_type ?? "unknown"}</li>
            <li>full_data: {analysis.full_data ? `present (${analysis.full_data.length} chars)` : "missing"}</li>
          </ul>
          <div className="mt-4 p-4 bg-gray-900 rounded-lg font-mono text-sm whitespace-pre-wrap max-h-96 overflow-y-auto">
            {analysis.root_cause}
          </div>
        </div>
      </div>
    );
  }

  const sev = enhancedData.summary.severity;
  const sevColor = getSevColor(sev);

  // ── Main view ──────────────────────────────────────────────────────────────
  return (
    <div style={{ display: "flex", flexDirection: "column", minHeight: "100%", fontFamily: sans }}>
      {showExport && (
        <ExportDrawer
          isOpen={showExport}
          onClose={() => setShowExport(false)}
          analysis={analysis}
          enhancedData={enhancedData}
          onExportMarkdown={handleExportMarkdown}
          onExportDocx={handleExportDocx}
          isExportingDocx={isExportingDocx}
        />
      )}

      {/* Back nav */}
      <div style={{ padding: "8px 24px", borderBottom: "1px solid rgba(255,255,255,0.04)", display: "flex", alignItems: "center", gap: "8px" }}>
        <button
          onClick={onBack}
          style={{ background: "none", border: "none", color: "#6b7280", fontSize: "12px", cursor: "pointer", fontFamily: mono, padding: 0, display: "inline-flex", alignItems: "center", gap: "4px" }}
        >
          ◀ Back to History
        </button>
        <span style={{ color: "#2a2a2e" }}>│</span>
        <span style={{ color: "#4b5563", fontSize: "12px", fontFamily: mono }}>{analysis.filename}</span>
      </div>

      {/* Header */}
      <div style={{ borderBottom: "1px solid rgba(255,255,255,0.06)", padding: "10px 24px", display: "flex", justifyContent: "space-between", alignItems: "center", background: "rgba(255,255,255,0.01)", flexWrap: "wrap", gap: "8px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: "12px", flexWrap: "wrap" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "7px" }}>
            <div style={{ width: "8px", height: "8px", borderRadius: "2px", background: sevColor }} />
            <span style={{ color: "#e5e7eb", fontSize: "14px", fontWeight: 700, fontFamily: mono }}>
              {format(new Date(analysis.analyzed_at), "yyyyMMdd")}-{String(analysis.id).padStart(4, "0")}
            </span>
          </div>
          <span style={{ display: "inline-flex", alignItems: "center", gap: "5px", background: `${sevColor}18`, color: sevColor, padding: "3px 10px", borderRadius: "4px", fontSize: "11px", fontWeight: 700, letterSpacing: ".08em", fontFamily: mono }}>
            <span style={{ fontSize: "6px" }}>⬤</span>{sev.toUpperCase()}
          </span>
          <span style={{ color: "#4b5563" }}>│</span>
          <span style={{ color: "#6b7280", fontSize: "12px" }}>{analysis.component ?? "Unknown component"}</span>
          <span style={{ color: "#4b5563" }}>│</span>
          <span style={{ color: "#6b7280", fontSize: "12px" }}>{format(new Date(analysis.analyzed_at), "dd MMM yyyy")}</span>
          <GoldBadge analysisId={analysis.id} isGold={isGold} onPromoted={() => setIsGold(true)} />
        </div>
        <div style={{ display: "flex", gap: "6px", alignItems: "center" }}>
          <button
            onClick={() => setExpanded(e => !e)}
            style={{
              background: expanded ? "rgba(139,92,246,0.12)" : "rgba(255,255,255,0.04)",
              border: `1px solid ${expanded ? "rgba(139,92,246,0.3)" : "rgba(255,255,255,0.1)"}`,
              color: expanded ? "#c4b5fd" : "#9ca3af",
              padding: "5px 12px", borderRadius: "6px", fontSize: "11px", cursor: "pointer", fontFamily: mono, transition: "all .2s",
            }}
          >
            {expanded ? "◉ Expanded" : "○ Standard"}
          </button>
          {jiraEnabled && (
            <button
              onClick={() => setShowJira(true)}
              style={{ background: "rgba(16,185,129,0.08)", border: "1px solid rgba(16,185,129,0.2)", color: "#6ee7b7", padding: "5px 12px", borderRadius: "6px", fontSize: "11px", cursor: "pointer", fontFamily: mono }}
            >
              ⊞ JIRA
            </button>
          )}
          <button
            onClick={() => setShowExport(true)}
            style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.1)", color: "#d1d5db", padding: "5px 12px", borderRadius: "6px", fontSize: "11px", cursor: "pointer", fontFamily: mono }}
          >
            ↗ Export
          </button>
        </div>
      </div>

      {/* Error banner */}
      <div style={{ padding: "8px 24px", background: "rgba(239,68,68,0.04)", borderBottom: "1px solid rgba(239,68,68,0.1)", display: "flex", alignItems: "center", gap: "10px", flexWrap: "wrap" }}>
        <span style={{ color: "#ef4444", fontSize: "12px", fontFamily: mono, fontWeight: 700 }}>{analysis.error_type}</span>
        {analysis.error_message && <>
          <span style={{ color: "#4b5563" }}>—</span>
          <span style={{ color: "#fca5a5", fontSize: "12px" }}>{analysis.error_message}</span>
        </>}
      </div>

      {/* Tabs */}
      <div style={{ display: "flex", borderBottom: "1px solid rgba(255,255,255,0.06)", padding: "0 24px", background: "rgba(255,255,255,0.01)", overflowX: "auto" }}>
        {TABS.map(t => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            style={{
              background: "none", border: "none",
              padding: "10px 18px",
              color: tab === t.id ? "#e5e7eb" : "#6b7280",
              fontSize: "12px", cursor: "pointer",
              borderBottom: tab === t.id ? "2px solid #e5e7eb" : "2px solid transparent",
              fontFamily: sans,
              fontWeight: tab === t.id ? 600 : 400,
              display: "inline-flex", alignItems: "center", gap: "5px",
              marginBottom: "-1px",
              transition: "color .15s",
              whiteSpace: "nowrap",
            }}
          >
            <span style={{ fontSize: "11px", opacity: tab === t.id ? 1 : 0.5 }}>{t.icon}</span>
            {t.label}
          </button>
        ))}
      </div>

      {/* Content */}
      <div style={{ flex: 1, overflowY: "auto", padding: "20px 24px", maxWidth: "1060px", width: "100%" }}>
        {tab === "support" && (
          <SupportTab
            analysis={analysis}
            enhancedData={enhancedData}
            expanded={expanded}
            editableRootCause={currentRootCause}
            onRootCauseSave={v => setEditableRootCause(v)}
          />
        )}
        {tab === "developer" && (
          <DeveloperTab
            analysis={analysis}
            enhancedData={enhancedData}
            expanded={expanded}
          />
        )}
        {tab === "customer" && (
          <CustomerTab analysis={analysis} enhancedData={enhancedData} />
        )}
        {tab === "executive" && (
          <ExecutiveTab analysis={analysis} enhancedData={enhancedData} expanded={expanded} />
        )}
      </div>

      {/* Sticky QActions (Expanded only) */}
      {expanded && (
        <QActions
          onExport={() => setShowExport(true)}
          onJira={jiraEnabled ? () => setShowJira(true) : undefined}
          analysisId={analysis.id}
          onGold={() => setIsGold(true)}
        />
      )}

      <JiraTicketModal analysis={analysis} isOpen={showJira} onClose={() => setShowJira(false)} />
    </div>
  );
}

// ── Quick Actions bar ──────────────────────────────────────────────────────
interface QActionsProps {
  onExport: () => void;
  onJira?: () => void;
  analysisId: number;
  onGold: () => void;
}

function QActions({ onExport, onJira, analysisId, onGold }: QActionsProps) {
  const [active, setActive] = useState<string | null>(null);
  const mono = "var(--hd-font-mono,'JetBrains Mono',monospace)";

  const fire = (id: string, fn?: () => void) => {
    fn?.();
    setActive(id);
    setTimeout(() => setActive(null), 2000);
  };

  const markGold = async () => {
    try {
      await invoke("promote_to_gold", { analysisId });
      onGold();
      fire("gold");
    } catch {
      fire("gold");
    }
  };

  const items = [
    ...(onJira ? [{ id: "jira",    label: "Create JIRA",        icon: "⊞", fn: onJira }] : []),
    { id: "gold",    label: "Add to Gold Answers",  icon: "◎", fn: markGold },
    { id: "export",  label: "Export",               icon: "↗", fn: onExport },
  ];

  return (
    <div style={{ position: "sticky", bottom: 0, background: "var(--hd-bg-base,#0a0a0c)", borderTop: "1px solid rgba(255,255,255,0.08)", padding: "10px 24px", display: "flex", justifyContent: "flex-end", gap: "6px", zIndex: 50 }}>
      {items.map(x => (
        <button
          key={x.id}
          onClick={() => fire(x.id, x.fn)}
          style={{
            background: active === x.id ? "rgba(16,185,129,0.12)" : "rgba(255,255,255,0.04)",
            border: `1px solid ${active === x.id ? "rgba(16,185,129,0.25)" : "rgba(255,255,255,0.08)"}`,
            color: active === x.id ? "#6ee7b7" : "#d1d5db",
            padding: "6px 12px", borderRadius: "6px", fontSize: "11px", cursor: "pointer", fontFamily: mono,
            display: "inline-flex", alignItems: "center", gap: "5px",
            transition: "all .15s",
          }}
        >
          <span>{x.icon}</span>
          {active === x.id ? "✓" : x.label}
        </button>
      ))}
    </div>
  );
}
